name: Pipeline CI/CD DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Validar Sintaxe
        run: |
          pip install -r requirements.txt
          python -m compileall .

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalando dependencias de seguranca
        run: pip install -r requirements.txt
      - name: Executar Bandit (SAST)
        run: bandit -r .
      - name: Executar pip-audit (SCA)
        run: pip-audit

  test:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Executar Testes Unitarios
        run: python -m unittest discover -s tests -v