name: Pipeline CI/CD Biblioteca

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Etapa de Build
      run: |
        echo "Executando Build da aplicação..."
        python -m compileall .

    - name: Executar Testes
      run: |
        python -m unittest discover -s tests -v

    - name: Etapa de Deploy
      run: |
        echo "Deploy realizado com sucesso!"